config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'tasks#index'
  resources :tasks
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/memo.rb
class Memo < ApplicationRecord
  belongs_to :task
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user
  has_one :memo,foreign_key: :task_id, dependent: :destroy
end

app/models/task_memo.rb
class TaskMemo
    include ActiveModel::Model
    attr_accessor :url,:region,:phone_number,:ceo,:content,:task_id,:id,:title,:user_id,:created_at,:updated_at
    with_options presence: true do
        validates :title
        validates :url
        validates :region
        validates :phone_number
        validates :ceo
        validates :content
        validates :user_id
      end

  
      delegate :persisted?, to: :task

      def initialize(attributes = nil, task: Task.new)
        @task = task
        attributes ||= default_attributes
        super(attributes)
      end
    
      def save
        return if invalid?
    
        ActiveRecord::Base.transaction do
          task.assign_attributes(title: title, user_id: user_id)
          memos =  Memo.new(url: url, region: region, phone_number: phone_number, ceo: ceo, content: content)
          task.memo = memos
          task.save!
        end
        rescue ActiveRecord::RecordInvalid
          false
      end
    
      def to_model
        task
      end
    
      private
    
      attr_reader :task
    
      def default_attributes
        {
          user_id: task.user_id,
          title: task.title,
          url: task.memo&.url,
          region: task.memo&.region,
          phone_number: task.memo&.phone_number,
          ceo: task.memo&.ceo,
          content: task.memo&.content
        }
      end
end

app/models/user.rb
class User < ApplicationRecord

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :nickname, presence: true, length: { maximum: 6 }
  validates :password, presence: true, length: { minimum: 6 }
  has_many :tasks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!
  before_action :basic_auth
  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == 'admin' && password == '2222'
  end
end

end

app/controllers/memos_controller.rb
class MemosController < ApplicationController
    def index
    end

    def new
    end

    def create
    end

    def show
      @memo= Memo.find(params[:id])
    end

    def edit
    end

    private

    def memo_params
      params.require(:memo).permit(:url,:region,:phone_number,:ceo,:content).merge(user_id: current_user.id,task_id: @task.id)
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks=Task.all
  end

  def new
    @task_memo = TaskMemo.new
  end


  def create
    task_memo =  TaskMemo.new(task_params)
    if task_memo.valid?
      task_memo.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    load_task

    @task_memo = TaskMemo.new(task: @task_memo)
  end

  def edit
    load_task

    @task_memo = TaskMemo.new(task: @task_memo)

  end

  def update
    load_task

    @form = TaskMemo.new(task_params, task: @task_memo)

    if @form.save
      redirect_to @task_memo, notice: 'The post has been updated.'
    else
      render :edit
    end
  end




  def destroy
    @task= Task.find(params[:id])
    redirect_to root_path if @task.destroy
  end


  private

  def task_params
    params.require(:task).permit(:title,:url,:region,:phone_number,:ceo,:content).merge(user_id: current_user.id)
  end


  def load_task
    @task_memo = current_user.tasks.find(params[:id])
  end
  

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/memos_helper.rb
module MemosHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ToDoApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <nav class="navbar" style="background-color: #e3f2fd;">
   <a class="navbar-brand" href="/">TO DO 転職</a>
  <% if user_signed_in? %>
    <div class="nav__right">
    <%="#{current_user.nickname}さん"%>
     <%= link_to'ログアウト',destroy_user_session_path,method: :delete%>
    </div> 
  <% else %>
    <div class="nav__right">
     <%= link_to'ログイン',new_user_session_path%>
     <%= link_to'新規登録',new_user_registration_path%>
    </div> 
  <% end %>
  </nav>
  <div class="container">
    <%= yield %>
  </div>
  </body>
</html>

app/views/layouts/new.html.erb
<%= form_with model: @donation_address, url: donations_path, local: true do |f| %>
  <%= render 'error_messages', model: @donation_address %>
  <h1>住所</h1>
  <div class="field">
   <%= f.label :postal_code, "郵便番号（ハイフンを含む）" %>
   <%= f.text_field :postal_code %>
  </div>
  <div class="field">
    <%= f.label :prefecture, "都道府県" %>
    <%= f.collection_select :prefecture, Prefecture.all, :id, :name %>
  </div>
  <div class="field">
    <%= f.label :city, "市町村（任意）" %>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :house_number, "番地（任意）" %>
    <%= f.text_field :house_number %>
  </div>
  <div class="field">
    <%= f.label :building_name, "建物名（任意）" %>
    <%= f.text_field :building_name %>
  </div>

  <h1>寄付</h1>
  <div class="field">
    <%= f.label :price, "金額（¥1~1,000,000）" %>
    <%= "¥" %>
    <%= f.text_field :price %>
  </div>

  <div class="actions">
    <%= f.submit "寄付する" %>
  </div>
<% end %>

app/views/memos/new.html.erb
<div class="contents row">
<tr>
  <div class="container">
  <%= form_with(model: [@task, @memo], local: true) do |f| %>
  <th>会社名</th>
  <td><%= @task.title%></td>
  <p></p>
</tr>
<tr>
<th>会社URL欄</th>
<td>
  <p><%= f.text_field :url, class:"input-default", id:"url", :size=>"60"%></p>
</td>
</tr>
<tr>
<div class="form-group">
<th>所在地</th>
<td>
  <p><%= f.text_field :region, class:"input-default", id:"region", placeholder:"埼玉県越谷市大林市5-10-11",:size=>"60"%></p>
</td>
</tr>
<tr>
<th>電話</th>
<td>
  <p><%= f.text_field :phone_number, class:"input-default", id:"phone_number", placeholder:"09012190274", maxlength:"11" %></p>
</td>
</tr>
<tr>
<th>代表者名</th>
<td>
  <p><%= f.text_field :CEO, class:"input-default", id:"CEO", placeholder:"例）牧野幹弘"%></p>
</td>
</tr>
<tr>
<th>記述</th>
<td>
  <p><%= f.text_area :content, class:"memo-text", id:"content", placeholder:"従業員は250名ほどです。勤務時間は09:00~18:00になります。仕事内容はシステムの保守・運用・開発まで多岐にわたります。" ,:size=>"60x10",maxlength:"1000" %></p>
</td>
</tr>
<tr>
<th>登録</th>
<td>
  <p><%= f.submit "CREATE" %></p>
</td>
</tr>
 <% end %>
</div>
</table>

  </div>
</div>

app/views/tasks/_form.html.erb
<%= form_with model: @task_memo, url: url,method: method,local: true  do |f| %>
<div class="contents row">
<div class="container">
<th>会社名</th>
  <p><%= f.text_field :title,class:"input-default", id:"title", :size=>"20"%></p>
<tr>
<th>会社URL欄</th>
<td>
  <p><%= f.text_field :url, class:"input-default", id:"url", :size=>"60"%></p>
</td>
</tr>
<tr>
<div class="form-group">
<th>所在地</th>
<td>
  <p><%= f.text_field :region, class:"input-default", id:"region",:size=>"60"%></p>
</td>
</tr>
<tr>
<th>電話</th>
<td>
  <p><%= f.text_field :phone_number, class:"input-default", id:"phone_number",  maxlength:"11" %></p>
</td>
</tr>
<tr>
<th>代表者名</th>
<td>
  <p><%= f.text_field :ceo, class:"input-default", id:"ceo"%></p>
</td>
</tr>
<tr>
<th>記述</th>
<td>
  <p><%= f.text_area :content, class:"memo-text", id:"content",:size=>"60x10",maxlength:"1000" %></p>
</td>
</tr>
<tr>
<td>
  <p><%= f.submit 'CREATE',class: "btn btn-outline-primary"%></p>
</td>
</tr>
</div>
</div>
<% end %>

app/views/tasks/edit.html.erb
<h2 class="title">TO EDIT THE COMPANY</h2>
<%= form_with model: @task_memo, local: true do |f| %>
<div class="contents row">
<div class="container">
<th>会社名</th>
  <p><%= f.text_field :title,class:"input-default", id:"title", :size=>"20"%></p>
<tr>
<th>会社URL欄</th>
<td>
  <p><%= f.text_field :url, class:"input-default", id:"url", :size=>"60"%></p>
</td>
</tr>
<tr>
<div class="form-group">
<th>所在地</th>
<td>
  <p><%= f.text_field :region, class:"input-default", id:"region",:size=>"60"%></p>
</td>
</tr>
<tr>
<th>電話</th>
<td>
  <p><%= f.text_field :phone_number, class:"input-default", id:"phone_number",  maxlength:"11" %></p>
</td>
</tr>
<tr>
<th>代表者名</th>
<td>
  <p><%= f.text_field :ceo, class:"input-default", id:"ceo"%></p>
</td>
</tr>
<tr>
<th>記述</th>
<td>
  <p><%= f.text_area :content, class:"memo-text", id:"content",:size=>"60x10",maxlength:"1000" %></p>
</td>
</tr>
<tr>
<td>
  <p><%= f.submit 'CREATE',class: "btn btn-outline-primary"%></p>
</td>
</tr>
</div>
</div>
<% end %>

app/views/tasks/index.html.erb
<%= link_to "CREATE NEW COMPANY",new_task_path,method: :GET,class: :"btn btn-primary", id: "create-new-task"%>
<h3>COMPANY LIST</h3>
<% @tasks.each do |task| %>
<% if user_signed_in? && current_user.id == task.user_id%>
     <p>・<%=link_to task.title,task_path(task.id)%>
    <%=link_to edit_task_path(task.id), method: :get do %>
    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-wrench-adjustable" viewBox="0 0 16 16">
    <path d="M16 4.5a4.492 4.492 0 0 1-1.703 3.526L13 5l2.959-1.11c.027.2.041.403.041.61Z"/>
    <path d="M11.5 9c.653 0 1.273-.139 1.833-.39L12 5.5 11 3l3.826-1.53A4.5 4.5 0 0 0 7.29 6.092l-6.116 5.096a2.583 2.583 0 1 0 3.638 3.638L9.908 8.71A4.49 4.49 0 0 0 11.5 9Zm-1.292-4.361-.596.893.809-.27a.25.25 0 0 1 .287.377l-.596.893.809-.27.158.475-1.5.5a.25.25 0 0 1-.287-.376l.596-.893-.809.27a.25.25 0 0 1-.287-.377l.596-.893-.809.27-.158-.475 1.5-.5a.25.25 0 0 1 .287.376ZM3 14a1 1 0 1 1 0-2 1 1 0 0 1 0 2Z"/>
    </svg>
    <% end %>
    <%=link_to task_path(task.id), method: :delete do %>
    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash" viewBox="0 0 16 16">
    <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/>
    <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"/>
    </svg>
    <% end %>
<% end %>
    </p>
<% end %>

app/views/tasks/new.html.erb
<h2 class="title">CREATE NEW COMPANY</h2>
<%= render partial: 'form', locals: {url: tasks_path, method: :post} %>

app/views/tasks/show.html.erb
<h2 class="title">COMPANY PROFILE</h2>
<div class="contents row">
<div class="container">
<th>会社名</th>
  <p><%= @task_memo.title%></p>
<tr>
<th>会社URL欄</th>
<td>
  <p><%= raw Rinku.auto_link((@task_memo.url), :urls, 'target="_blank"')%></p>
</td>
</tr>
<tr>
<div class="form-group">
<th>所在地</th>
<td>
  <p><%=@task_memo.region %></p>
</td>
</tr>
<tr>
<th>電話</th>
<td>
  <p><%=@task_memo.phone_number%></p>
</td>
</tr>
<tr>
<th>代表者名</th>
<td>
  <p><%= @task_memo.ceo%></p>
</td>
</tr>
<tr>
<th>記述</th>
<td>
  <p><%=@task_memo.content%></p>
</td>
</tr>
<tr>
<td>
</td>
</tr>
</div>
</table>

</div>